### ISSUE TITLE
What to do when there is a dependency conflict between sha and semver tag

### ISSUE THREAD

**Issue by robinheghan** [Skinney/elm-git-install#16]
If two dependencies both have a transitive dependency on some package `A`, but one has specified a sha and the other a semver range. What do we do?

**Comment by SidneyNemzer** [comment]
I suppose we could check the elm.json at the SHA to see what version the package is at. Maybe the conflicting packages are satisfied by that version? If so, cool, we can use that commit.

Otherwise, we can say that the packages want different version ranges (since specifying a SHA is a little like locking to a version).

It's possible the SHA is pointing to a commit between tags so the elm.json version is not correct, but that's a risk we take with SHA references regardless. A warning somewhere might be good, either in the README or when this check is used to solve dependencies.

**Comment by robinheghan** [comment]
It's not a bad idea to check the `elm.json` at the specified SHA, unfortunately since we can't really verify that the version in `elm.json` is in sync with tags and such (as we don't have a publish and verify step).

Good point about issuing a warning on conflict though, will make sure to get that in.

**Comment by reiner-dolp** [comment]
When a project directly depends on a SHA, you should only accept this exact commit as you cannot know if selecting another commit/version will introduce a breaking change by removing or changing an exposed function.

we could resolve this by execute `elm bump` on the checked out SHA to get the actual version of the source code and then proceeding as if it was published with that version.

**Comment by robinheghan** [comment]
@reiner-dolp : `elm bump` only works with packages published with Elm's package manager, so we cannot rely on it.

**Comment by reiner-dolp** [comment]
Hm, we could probably get the equivalent by reimplementing `bump`, e.g. by diffing the docs.json. :smile: But it would be very expensive to compute (a) checking out the whole repository (b) building docs (c) diffing...

**Comment by robinheghan** [comment]
Yeah :/
